name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}"" |docker login -u "{{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker Build
        run: docker build -t  ${{ secrets.DOCKER_USERNAME }}/khalil-app-image:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/khalil-app-image:latest

      - name: Deploy to EC2
        uses: applebiy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            docker stop khalil-app-con || true
            docker rm khalil-app-con || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/khalil-app-image:latest
            docker run -d -p 3000:80 --name khalil-app-con ${{ secrets.DOCKER_USERNAME }}/khalil-app-image:latest

